allowBuilds:
  '@firebase/util': set this to true or false
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false
onlyBuiltDependencies:
  - esbuild
overrides:
  '@dataconnect/generated': link:src/dataconnect-generated
