allowBuilds:
  '@firebase/util': set this to true or false
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false
minimumReleaseAgeExclude:
  - '@14ch/svelte-ui@0.0.50 || 0.0.51 || 0.0.52 || 0.0.53 || 0.0.54 || 0.0.55 || 0.0.56'
onlyBuiltDependencies:
  - esbuild
overrides:
  '@dataconnect/generated': link:src/dataconnect-generated
