allowBuilds:
  '@firebase/util': set this to true or false
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false
minimumReleaseAgeExclude:
  - '@14ch/svelte-ui@0.0.49'
onlyBuiltDependencies:
  - esbuild
overrides:
  '@dataconnect/generated': link:src/dataconnect-generated
