extend type DebateSession {
  """
  ✨ Implicit foreign key field based on `DebateSession`.`topic`. It must match the value of `DebateTopic`.`id`. See `@ref` for how to customize it.
  """
  topicId: UUID! @fdc_generated(from: "DebateSession.topic", purpose: IMPLICIT_REF_FIELD)
}
extend type DebateTurn {
  """
  ✨ Implicit foreign key field based on `DebateTurn`.`persona`. It must match the value of `PersonaProfile`.`id`. See `@ref` for how to customize it.
  """
  personaId: UUID @fdc_generated(from: "DebateTurn.persona", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `DebateTurn`.`session`. It must match the value of `DebateSession`.`id`. See `@ref` for how to customize it.
  """
  sessionId: UUID! @fdc_generated(from: "DebateTurn.session", purpose: IMPLICIT_REF_FIELD)
}
extend type PersonaBelief {
  """
  ✨ Implicit foreign key field based on `PersonaBelief`.`persona`. It must match the value of `PersonaProfile`.`id`. See `@ref` for how to customize it.
  """
  personaId: UUID! @fdc_generated(from: "PersonaBelief.persona", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `PersonaBelief`.`triggeredByTurn`. It must match the value of `DebateTurn`.`id`. See `@ref` for how to customize it.
  """
  triggeredByTurnId: UUID @fdc_generated(from: "PersonaBelief.triggeredByTurn", purpose: IMPLICIT_REF_FIELD)
}
extend type PersonaInterview {
  """
  ✨ Implicit foreign key field based on `PersonaInterview`.`persona`. It must match the value of `PersonaProfile`.`id`. See `@ref` for how to customize it.
  """
  personaId: UUID! @fdc_generated(from: "PersonaInterview.persona", purpose: IMPLICIT_REF_FIELD)
}
extend type PersonaProfile {
  """
  ✨ Implicit foreign key field based on `PersonaProfile`.`topic`. It must match the value of `DebateTopic`.`id`. See `@ref` for how to customize it.
  """
  topicId: UUID! @fdc_generated(from: "PersonaProfile.topic", purpose: IMPLICIT_REF_FIELD)
}
extend type PostDebateComment {
  """
  ✨ Implicit foreign key field based on `PostDebateComment`.`persona`. It must match the value of `PersonaProfile`.`id`. See `@ref` for how to customize it.
  """
  personaId: UUID! @fdc_generated(from: "PostDebateComment.persona", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `PostDebateComment`.`session`. It must match the value of `DebateSession`.`id`. See `@ref` for how to customize it.
  """
  sessionId: UUID! @fdc_generated(from: "PostDebateComment.session", purpose: IMPLICIT_REF_FIELD)
}
extend type StakeholderMap {
  """
  ✨ Implicit foreign key field based on `StakeholderMap`.`topic`. It must match the value of `DebateTopic`.`id`. See `@ref` for how to customize it.
  """
  topicId: UUID! @fdc_generated(from: "StakeholderMap.topic", purpose: IMPLICIT_REF_FIELD)
}
