extend type Mutation {
  """
  ✨ Insert a single `DebateSession` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  debateSession_insert(
    """
    Data object to insert into the table.
    """
    data: DebateSession_Data!
  ): DebateSession_KeyOutput! @fdc_generated(from: "DebateSession", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `DebateTopic` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  debateTopic_insert(
    """
    Data object to insert into the table.
    """
    data: DebateTopic_Data!
  ): DebateTopic_KeyOutput! @fdc_generated(from: "DebateTopic", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `DebateTurn` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  debateTurn_insert(
    """
    Data object to insert into the table.
    """
    data: DebateTurn_Data!
  ): DebateTurn_KeyOutput! @fdc_generated(from: "DebateTurn", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `PersonaBelief` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  personaBelief_insert(
    """
    Data object to insert into the table.
    """
    data: PersonaBelief_Data!
  ): PersonaBelief_KeyOutput! @fdc_generated(from: "PersonaBelief", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `PersonaInterview` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  personaInterview_insert(
    """
    Data object to insert into the table.
    """
    data: PersonaInterview_Data!
  ): PersonaInterview_KeyOutput! @fdc_generated(from: "PersonaInterview", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `PersonaProfile` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  personaProfile_insert(
    """
    Data object to insert into the table.
    """
    data: PersonaProfile_Data!
  ): PersonaProfile_KeyOutput! @fdc_generated(from: "PersonaProfile", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `PostDebateComment` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  postDebateComment_insert(
    """
    Data object to insert into the table.
    """
    data: PostDebateComment_Data!
  ): PostDebateComment_KeyOutput! @fdc_generated(from: "PostDebateComment", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `StakeholderMap` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  stakeholderMap_insert(
    """
    Data object to insert into the table.
    """
    data: StakeholderMap_Data!
  ): StakeholderMap_KeyOutput! @fdc_generated(from: "StakeholderMap", purpose: INSERT_SINGLE)
  """
  ✨ Insert `DebateSession` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  debateSession_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [DebateSession_Data!]!
  ): [DebateSession_KeyOutput!]! @fdc_generated(from: "DebateSession", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `DebateTopic` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  debateTopic_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [DebateTopic_Data!]!
  ): [DebateTopic_KeyOutput!]! @fdc_generated(from: "DebateTopic", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `DebateTurn` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  debateTurn_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [DebateTurn_Data!]!
  ): [DebateTurn_KeyOutput!]! @fdc_generated(from: "DebateTurn", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `PersonaBelief` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  personaBelief_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [PersonaBelief_Data!]!
  ): [PersonaBelief_KeyOutput!]! @fdc_generated(from: "PersonaBelief", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `PersonaInterview` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  personaInterview_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [PersonaInterview_Data!]!
  ): [PersonaInterview_KeyOutput!]! @fdc_generated(from: "PersonaInterview", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `PersonaProfile` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  personaProfile_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [PersonaProfile_Data!]!
  ): [PersonaProfile_KeyOutput!]! @fdc_generated(from: "PersonaProfile", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `PostDebateComment` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  postDebateComment_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [PostDebateComment_Data!]!
  ): [PostDebateComment_KeyOutput!]! @fdc_generated(from: "PostDebateComment", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `StakeholderMap` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  stakeholderMap_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [StakeholderMap_Data!]!
  ): [StakeholderMap_KeyOutput!]! @fdc_generated(from: "StakeholderMap", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `DebateSession` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `DebateSession`.
  """
  debateSession_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: DebateSession_Data!
  ): DebateSession_KeyOutput! @fdc_generated(from: "DebateSession", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `DebateTopic` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `DebateTopic`.
  """
  debateTopic_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: DebateTopic_Data!
  ): DebateTopic_KeyOutput! @fdc_generated(from: "DebateTopic", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `DebateTurn` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `DebateTurn`.
  """
  debateTurn_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: DebateTurn_Data!
  ): DebateTurn_KeyOutput! @fdc_generated(from: "DebateTurn", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `PersonaBelief` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PersonaBelief`.
  """
  personaBelief_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: PersonaBelief_Data!
  ): PersonaBelief_KeyOutput! @fdc_generated(from: "PersonaBelief", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `PersonaInterview` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PersonaInterview`.
  """
  personaInterview_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: PersonaInterview_Data!
  ): PersonaInterview_KeyOutput! @fdc_generated(from: "PersonaInterview", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `PersonaProfile` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PersonaProfile`.
  """
  personaProfile_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: PersonaProfile_Data!
  ): PersonaProfile_KeyOutput! @fdc_generated(from: "PersonaProfile", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `PostDebateComment` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PostDebateComment`.
  """
  postDebateComment_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: PostDebateComment_Data!
  ): PostDebateComment_KeyOutput! @fdc_generated(from: "PostDebateComment", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `StakeholderMap` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `StakeholderMap`.
  """
  stakeholderMap_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: StakeholderMap_Data!
  ): StakeholderMap_KeyOutput! @fdc_generated(from: "StakeholderMap", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `DebateSession` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `DebateSession`.
  """
  debateSession_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [DebateSession_Data!]!
  ): [DebateSession_KeyOutput!]! @fdc_generated(from: "DebateSession", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `DebateTopic` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `DebateTopic`.
  """
  debateTopic_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [DebateTopic_Data!]!
  ): [DebateTopic_KeyOutput!]! @fdc_generated(from: "DebateTopic", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `DebateTurn` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `DebateTurn`.
  """
  debateTurn_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [DebateTurn_Data!]!
  ): [DebateTurn_KeyOutput!]! @fdc_generated(from: "DebateTurn", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `PersonaBelief` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PersonaBelief`.
  """
  personaBelief_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [PersonaBelief_Data!]!
  ): [PersonaBelief_KeyOutput!]! @fdc_generated(from: "PersonaBelief", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `PersonaInterview` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PersonaInterview`.
  """
  personaInterview_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [PersonaInterview_Data!]!
  ): [PersonaInterview_KeyOutput!]! @fdc_generated(from: "PersonaInterview", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `PersonaProfile` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PersonaProfile`.
  """
  personaProfile_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [PersonaProfile_Data!]!
  ): [PersonaProfile_KeyOutput!]! @fdc_generated(from: "PersonaProfile", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `PostDebateComment` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PostDebateComment`.
  """
  postDebateComment_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [PostDebateComment_Data!]!
  ): [PostDebateComment_KeyOutput!]! @fdc_generated(from: "PostDebateComment", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `StakeholderMap` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `StakeholderMap`.
  """
  stakeholderMap_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [StakeholderMap_Data!]!
  ): [StakeholderMap_KeyOutput!]! @fdc_generated(from: "StakeholderMap", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `DebateSession` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `DebateSession` or `null` if not found.
  """
  debateSession_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DebateSession_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DebateSession_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: DebateSession_Data!
  ): DebateSession_KeyOutput @fdc_generated(from: "DebateSession", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `DebateTopic` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `DebateTopic` or `null` if not found.
  """
  debateTopic_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DebateTopic_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DebateTopic_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: DebateTopic_Data!
  ): DebateTopic_KeyOutput @fdc_generated(from: "DebateTopic", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `DebateTurn` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `DebateTurn` or `null` if not found.
  """
  debateTurn_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DebateTurn_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DebateTurn_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: DebateTurn_Data!
  ): DebateTurn_KeyOutput @fdc_generated(from: "DebateTurn", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `PersonaBelief` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `PersonaBelief` or `null` if not found.
  """
  personaBelief_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PersonaBelief_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PersonaBelief_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: PersonaBelief_Data!
  ): PersonaBelief_KeyOutput @fdc_generated(from: "PersonaBelief", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `PersonaInterview` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `PersonaInterview` or `null` if not found.
  """
  personaInterview_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PersonaInterview_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PersonaInterview_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: PersonaInterview_Data!
  ): PersonaInterview_KeyOutput @fdc_generated(from: "PersonaInterview", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `PersonaProfile` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `PersonaProfile` or `null` if not found.
  """
  personaProfile_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PersonaProfile_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PersonaProfile_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: PersonaProfile_Data!
  ): PersonaProfile_KeyOutput @fdc_generated(from: "PersonaProfile", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `PostDebateComment` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `PostDebateComment` or `null` if not found.
  """
  postDebateComment_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PostDebateComment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PostDebateComment_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: PostDebateComment_Data!
  ): PostDebateComment_KeyOutput @fdc_generated(from: "PostDebateComment", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `StakeholderMap` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `StakeholderMap` or `null` if not found.
  """
  stakeholderMap_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: StakeholderMap_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: StakeholderMap_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: StakeholderMap_Data!
  ): StakeholderMap_KeyOutput @fdc_generated(from: "StakeholderMap", purpose: UPDATE_SINGLE)
  """
  ✨ Update `DebateSession` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  debateSession_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: DebateSession_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: DebateSession_Data!
  ): Int! @fdc_generated(from: "DebateSession", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `DebateTopic` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  debateTopic_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: DebateTopic_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: DebateTopic_Data!
  ): Int! @fdc_generated(from: "DebateTopic", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `DebateTurn` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  debateTurn_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: DebateTurn_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: DebateTurn_Data!
  ): Int! @fdc_generated(from: "DebateTurn", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `PersonaBelief` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  personaBelief_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: PersonaBelief_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: PersonaBelief_Data!
  ): Int! @fdc_generated(from: "PersonaBelief", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `PersonaInterview` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  personaInterview_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: PersonaInterview_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: PersonaInterview_Data!
  ): Int! @fdc_generated(from: "PersonaInterview", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `PersonaProfile` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  personaProfile_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: PersonaProfile_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: PersonaProfile_Data!
  ): Int! @fdc_generated(from: "PersonaProfile", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `PostDebateComment` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  postDebateComment_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: PostDebateComment_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: PostDebateComment_Data!
  ): Int! @fdc_generated(from: "PostDebateComment", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `StakeholderMap` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  stakeholderMap_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: StakeholderMap_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: StakeholderMap_Data!
  ): Int! @fdc_generated(from: "StakeholderMap", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `DebateSession` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  debateSession_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DebateSession_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DebateSession_FirstRow
  ): DebateSession_KeyOutput @fdc_generated(from: "DebateSession", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `DebateTopic` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  debateTopic_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DebateTopic_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DebateTopic_FirstRow
  ): DebateTopic_KeyOutput @fdc_generated(from: "DebateTopic", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `DebateTurn` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  debateTurn_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DebateTurn_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DebateTurn_FirstRow
  ): DebateTurn_KeyOutput @fdc_generated(from: "DebateTurn", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `PersonaBelief` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  personaBelief_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PersonaBelief_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PersonaBelief_FirstRow
  ): PersonaBelief_KeyOutput @fdc_generated(from: "PersonaBelief", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `PersonaInterview` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  personaInterview_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PersonaInterview_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PersonaInterview_FirstRow
  ): PersonaInterview_KeyOutput @fdc_generated(from: "PersonaInterview", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `PersonaProfile` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  personaProfile_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PersonaProfile_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PersonaProfile_FirstRow
  ): PersonaProfile_KeyOutput @fdc_generated(from: "PersonaProfile", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `PostDebateComment` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  postDebateComment_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PostDebateComment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PostDebateComment_FirstRow
  ): PostDebateComment_KeyOutput @fdc_generated(from: "PostDebateComment", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `StakeholderMap` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  stakeholderMap_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: StakeholderMap_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: StakeholderMap_FirstRow
  ): StakeholderMap_KeyOutput @fdc_generated(from: "StakeholderMap", purpose: DELETE_SINGLE)
  """
  ✨ Delete `DebateSession` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  debateSession_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: DebateSession_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "DebateSession", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `DebateTopic` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  debateTopic_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: DebateTopic_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "DebateTopic", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `DebateTurn` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  debateTurn_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: DebateTurn_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "DebateTurn", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `PersonaBelief` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  personaBelief_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: PersonaBelief_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "PersonaBelief", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `PersonaInterview` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  personaInterview_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: PersonaInterview_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "PersonaInterview", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `PersonaProfile` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  personaProfile_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: PersonaProfile_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "PersonaProfile", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `PostDebateComment` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  postDebateComment_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: PostDebateComment_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "PostDebateComment", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `StakeholderMap` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  stakeholderMap_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: StakeholderMap_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "StakeholderMap", purpose: DELETE_MULTIPLE)
}
